# Generated by Django 2.2.2 on 2021-09-14 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_auto_20210905_1745'),
        ('personas', '0002_auto_20210901_0018'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.IntegerField(choices=[(1, 'TICKET'), (2, 'FACTURA')], default=2)),
                ('numero_comprobante', models.CharField(max_length=100, verbose_name='Numero Comprobante')),
                ('impuesto', models.IntegerField(blank=True, choices=[(5, '5%'), (10, '10%')], null=True)),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('estado', models.IntegerField(choices=[(1, 'CREADO'), (2, 'APROBADO'), (3, 'RECHAZADO')], default=1)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.Proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden Compra',
                'verbose_name_plural': 'Ordenes de Compra',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimientos.OrdenCompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Producto')),
            ],
            options={
                'verbose_name': 'Orden Compra Detalle',
                'verbose_name_plural': 'Ordenes de Compra Detalle',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimientos.Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Producto')),
            ],
            options={
                'verbose_name': 'Compra Detalle',
                'verbose_name_plural': 'Compra Detalle',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movimientos.OrdenCompra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.Proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
