# Generated by Django 2.2.2 on 2021-09-15 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero Comprobante'),
        ),
    ]
