# Generated by Django 2.2.2 on 2021-10-08 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20210901_0018'),
        ('productos', '0006_auto_20211008_1714'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movimientos', '0002_auto_20210915_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.IntegerField(choices=[(1, 'TICKET'), (2, 'FACTURA')], default=2)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero Comprobante')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('impuesto', models.IntegerField(blank=True, choices=[(5, '5%'), (10, '10%')], null=True)),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('precio_venta', models.FloatField(verbose_name='Precio Venta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movimientos.Venta')),
            ],
            options={
                'verbose_name': 'Venta Detalle',
                'verbose_name_plural': 'Ventas Detalle',
                'ordering': ['-pk'],
            },
        ),
    ]
