# Generated by Django 2.2.2 on 2021-10-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_venta_ventadetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='impuesto',
        ),
        migrations.AddField(
            model_name='compra',
            name='condicion',
            field=models.IntegerField(choices=[(1, 'CONTADO'), (2, 'CREDITO')], default=1),
        ),
        migrations.AddField(
            model_name='compradetalle',
            name='impuesto',
            field=models.IntegerField(choices=[(5, '5%'), (10, '10%'), (0, 'EXCENTA')], default=10),
        ),
    ]
