# Generated by Django 2.2.2 on 2021-10-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0004_auto_20211021_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='total_excenta',
            field=models.FloatField(default=0, verbose_name='Total Excenta'),
        ),
        migrations.AddField(
            model_name='compra',
            name='total_iva10',
            field=models.FloatField(default=0, verbose_name='Total IVA 10%'),
        ),
        migrations.AddField(
            model_name='compra',
            name='total_iva5',
            field=models.FloatField(default=0, verbose_name='Total IVA 5%'),
        ),
    ]
