# Generated by Django 2.2.2 on 2021-11-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0005_auto_20211025_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='condicion',
            field=models.IntegerField(choices=[(1, 'CONTADO'), (2, 'CREDITO')], default=1),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_excenta',
            field=models.FloatField(default=0, verbose_name='Total Excenta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_iva10',
            field=models.FloatField(default=0, verbose_name='Total IVA 10%'),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_iva5',
            field=models.FloatField(default=0, verbose_name='Total IVA 5%'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='impuesto',
            field=models.IntegerField(choices=[(5, '5%'), (10, '10%'), (0, 'EXCENTA')], default=10),
        ),
    ]
