# Generated by Django 2.2.2 on 2021-11-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0006_auto_20211107_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-pk'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
