# Generated by Django 2.2.2 on 2021-11-20 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0007_auto_20211107_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('monto', models.FloatField(default=0, verbose_name='Total')),
                ('tipo', models.IntegerField(choices=[(1, 'APERTURA'), (2, 'CIERRE')], default=1)),
                ('facturas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facturas')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-pk'],
            },
        ),
    ]
