# Generated by Django 2.2.2 on 2021-11-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0009_caja_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
