# Generated by Django 2.2.2 on 2021-11-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0010_auto_20211121_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.IntegerField(choices=[(1, 'COMPRA'), (2, 'VENTA')], default=2, verbose_name='Tipo')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movimientos.Caja')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movimientos.Compra')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movimientos.Venta')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-pk'],
            },
        ),
    ]
