# Generated by Django 2.2.2 on 2021-11-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0012_auto_20211121_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='impuesto',
            field=models.IntegerField(blank=True, choices=[(5, '5%'), (10, '10%'), (0, 'EXCENTA')], null=True),
        ),
    ]
