# Generated by Django 2.2.2 on 2021-11-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0013_auto_20211124_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=64, verbose_name='Número')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de finalización')),
                ('codigo_establecimiento', models.CharField(max_length=32, verbose_name='Código de establecimiento')),
                ('punto_expedicion', models.CharField(max_length=32, verbose_name='Punto de expedición')),
                ('cantidad', models.IntegerField()),
                ('rango_inicio', models.IntegerField()),
                ('rango_fin', models.IntegerField()),
                ('secuencia_actual', models.IntegerField()),
                ('default', models.BooleanField(default=False)),
            ],
        ),
    ]
