# Generated by Django 2.2.2 on 2021-11-24 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0014_timbrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='timbrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movimientos.Timbrado'),
        ),
    ]
