# Generated by Django 2.2.2 on 2021-08-24 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Producto',
                'verbose_name_plural': 'Categorias de Productos',
                'ordering': ['-pk'],
                'permissions': [('activar_categoriaproducto', 'Puede Activar Categoria Producto'), ('inactivar_categoriaproducto', 'Puede Inactivar Categoria Producto')],
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Deposito de Producto',
                'verbose_name_plural': 'Depositos de Productos',
                'ordering': ['-pk'],
                'permissions': [('activar_deposito', 'Puede Activar Deposito'), ('inactivar_deposito', 'Puede Inactivar Deposito')],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Nombre o Razón Social')),
                ('ruc', models.CharField(max_length=20, verbose_name='RUC')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['-pk'],
                'permissions': [('activar_linea', 'Puede Activar Proveedor'), ('inactivar_linea', 'Puede Inactivar Proveedor')],
            },
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de medida de Producto',
                'verbose_name_plural': 'Unidades de medidas de Productos',
                'ordering': ['-pk'],
                'permissions': [('activar_unidaddemedida', 'Puede Activar Unidad de Medida'), ('inactivar_unidaddemedida', 'Puede Inactivar Unidad de Medida')],
            },
        ),
        migrations.CreateModel(
            name='SubCategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Categoria')),
            ],
            options={
                'verbose_name': 'Sub-Categoria de Producto',
                'verbose_name_plural': 'Sub-Categorias de Producto',
                'ordering': ['-pk'],
                'permissions': [('activar_subcategoriaproducto', 'Puede Activar SubCategoria Producto'), ('inactivar_subcategoriaproducto', 'Puede Inactivar SubCategoria Producto')],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción')),
                ('fecha_ultima_compra', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Última Compra')),
                ('fecha_modificacion_precio_venta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Modificación Precio Venta')),
                ('precio_compra', models.FloatField(verbose_name='Precio Compra')),
                ('precio_venta', models.FloatField(verbose_name='Precio Venta')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('cantidad_minima_stock', models.FloatField(verbose_name='Cantidad Minima Stock')),
                ('activo', models.BooleanField(default=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Deposito')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.Proveedor')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.SubCategoriaProducto')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.UnidadDeMedida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-pk'],
                'permissions': [('activar_producto', 'Puede Activar Producto'), ('inactivar_producto', 'Puede Inactivar Producto')],
            },
        ),
    ]
