# Generated by Django 2.2.2 on 2021-09-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.Proveedor'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
