# Generated by Django 2.2.2 on 2021-09-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20210905_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='porcentaje_ganancia',
            field=models.FloatField(default=0, verbose_name='Porcentaje Ganancia'),
        ),
    ]
