# Generated by Django 2.2.2 on 2021-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_transaccionproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionproducto',
            name='precio_venta_anterior',
            field=models.FloatField(default=0, verbose_name='Precio Venta Anterior'),
        ),
    ]
