# Generated by Django 2.2.2 on 2021-10-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_transaccionproducto_precio_venta_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccionproducto',
            name='precio_venta',
            field=models.FloatField(verbose_name='Precio Venta'),
        ),
    ]
