# Generated by Django 2.2.2 on 2021-11-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_producto_impuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='impuesto',
            field=models.IntegerField(choices=[(5, '5%'), (10, '10%'), (0, 'EXCENTA')], default=10),
        ),
    ]
