# Generated by Django 2.2.2 on 2021-09-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-pk'], 'permissions': [('activar_cliente', 'Puede Activar Cliente'), ('inactivar_cliente', 'Puede Inactivar Cliente')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['-pk'], 'permissions': [('activar_proveedor', 'Puede Activar Proveedor'), ('inactivar_proveedor', 'Puede Inactivar Proveedor')], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='comentario_desactivado',
        ),
    ]
